[package]
name = "hsip-cli"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
hex = "0.4"
argon2 = "0.5"
rand = "0.8"
chacha20poly1305 = "0.10"
base64 = "0.21"
rpassword = "7"


# existing deps
ed25519-dalek = { version = "2", features = ["rand_core"] }
dirs = "5"

hsip-core = { path = "../hsip-core" }
hsip-net  = { path = "../hsip-net" }
hsip-reputation = { path = "../hsip-reputation" }
