[package]
name = "hsip-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ed25519-dalek = "2"

hsip-core = { path = "../hsip-core" }
hsip-net  = { path = "../hsip-net" }
hsip-reputation = { path = "../hsip-reputation" }
