[workspace]
members = [
    "crates/hsip-core",
    "crates/hsip-session",
    "crates/hsip-net",
    "crates/hsip-reputation",
    "crates/hsip-cli",
]
exclude = [
    "crates/hsip-session/fuzz"
]
resolver = "2"
