[package]
name = "hsip-gateway"
version = "0.1.0"
edition = "2021"
license-file = "../LICENSE"

[dependencies]
anyhow = "1"
dirs = "5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
